version: 0.2

phases:
  install:
    commands:
      - echo Ensure the latest awscli is installed...
      - sudo pip install --upgrade awscli
      - echo Install AWS ECS CLI
      - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
      - sudo chmod +x /usr/local/bin/ecs-cli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-app .
      - docker tag my-app:latest 766884914534.dkr.ecr.ca-central-1.amazonaws.com/my-app:latest
      - docker push 766884914534.dkr.ecr.ca-central-1.amazonaws.com/my-app:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Restart the ECS Task to get the newly created image
      - aws ecs stop-task --cluster my-app-cluster --task-definition my-app:1
